feat: base api for 'idea' model
AlexeiKap/Ideas-app-backend pull request #1
Opened 2022-01-24 12:32 UTC by AlexeiKap

2022-01-24 12:36 UTC, AndreyAnischik requested changes

2022-01-24 12:36 UTC, AndreyAnischik commented on db/seeds.rb
> +p 'Seeds'
remove extra p

2022-01-24 12:36 UTC, AndreyAnischik commented
why did you remove serializer for Idea?

2022-01-24 12:38 UTC, AndreyAnischik requested changes

2022-01-24 12:38 UTC, AndreyAnischik commented on spec/requests/idea_spec.rb
> +      expect{
use `do end` structure for multiline blocks

2022-01-24 14:42 UTC, AlexeiKap commented
@AndreyAnischik "why did you remove serializer for Idea?"
temporary solution, testing the connection with the front

2022-01-27 12:29 UTC, AndreyAnischik commented on app/controllers/api/v1/statistics_controller.rb
> +        @statistic = Statistic.where(idea_id: params[:idea_id])
won't the array be returned here?

2022-01-27 12:32 UTC, AndreyAnischik commented on app/controllers/api/v1/reviews_controller.rb
> +      def get_reviews
maybe it is better to move this method to ideas_controller? and name method `revies` and just do `@idea.reviews`

2022-01-27 12:33 UTC, AndreyAnischik commented on config/routes.rb
> +      get '/reviews/get', to: 'reviews#get_reviews'
this should be moved to ideas. also please read about `collection` and `member` in routes and use them

2022-01-27 12:56 UTC, AlexeiKap commented on app/controllers/api/v1/statistics_controller.rb
> +        @statistic = Statistic.where(idea_id: params[:idea_id])
@AndreyAnischik Yes, you are right. Fixed it

2022-01-31 10:15 UTC, AndreyAnischik requested changes

2022-01-31 10:15 UTC, AndreyAnischik commented on app/controllers/api/v1/reviews_controller.rb
> +        @reviews = Review.new(review_params)
why is it plural?

2022-01-31 10:15 UTC, AndreyAnischik commented on app/controllers/application_controller.rb
> +    head :forbidden unless user_signed_in? && current_user.role == 'creator'
make it work like `current_user.creator?` and below like `current_user.investor?`

2022-01-31 10:15 UTC, AndreyAnischik commented on app/models/idea.rb
> +  def status_is_published?
rename it to just `published?`. also, make the idea work like `self.published?` instead of `status == 'published'`

2022-01-31 10:15 UTC, AndreyAnischik commented on app/models/user.rb
> +  def creator?
use define_method to generate such creator? and investor?

2022-01-31 14:36 UTC, merged